version: "3.8"

services:
  client:
    container_name: "Bin2Dec"
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - "./:/app"
      - "/app/node_modules"
